spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gymdb
    username: root
    password: 8515830
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false


#server:
#  port: 8888

mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo